// GENERATED by scripts/build-playgrounds-app.py — edit the original, not this copy.
import Foundation

/// Text for the interruption screen. Deliberately plain: no imagery, no
/// streaks, no "watch one more" option.
public struct BlockScreenCopy: Codable, Equatable, Sendable {
    public var title: String
    public var message: String
    public var detail: String
    public var buttonTitle: String

    public init(title: String, message: String, detail: String, buttonTitle: String = "Back to Instagram") {
        self.title = title
        self.message = message
        self.detail = detail
        self.buttonTitle = buttonTitle
    }

    static let intentionalDetail =
        "You can still watch Reels that you intentionally open from people you follow or receive from friends."

    public init(reason: BlockReason, locale: Locale = .current, timeZone: TimeZone = .current) {
        switch reason {
        case .notFollowed:
            self.init(title: "Reels Blocked",
                      message: "This Reel isn't from an account you follow.",
                      detail: Self.intentionalDetail)
        case .infiniteScroll:
            self.init(title: "That's enough Reels for now.",
                      message: "Instagram tried to keep the Reels going, and this one couldn't be confirmed as coming from someone you follow.",
                      detail: Self.intentionalDetail)
        case .endOfSentReel:
            self.init(title: "That's the Reel you were sent.",
                      message: "Scrolling past it would start Instagram's Reels feed, so it stops here.",
                      detail: "You can still open other Reels your friends send you.")
        case .recommended:
            self.init(title: "Reels Blocked",
                      message: "This Reel was recommended by Instagram.",
                      detail: Self.intentionalDetail)
        case .reelsFeed:
            self.init(title: "That's enough Reels for now.",
                      message: "The Reels feed is made of recommendations, not things you chose.",
                      detail: Self.intentionalDetail)
        case .explore:
            self.init(title: "Explore is off",
                      message: "Strict Mode blocks the Explore page.",
                      detail: Self.intentionalDetail)
        case let .categoryDisabled(category):
            let what: String
            switch category {
            case .following: what = "Reels from people you follow"
            case .sentToMe: what = "Reels sent to you"
            case .profiles: what = "Reels opened from profiles"
            }
            self.init(title: "Reels Blocked",
                      message: "\(what) are turned off.",
                      detail: "You can change this in Reels Guard.")
        case let .timeUp(until):
            let formatter = DateFormatter()
            formatter.locale = locale
            formatter.timeZone = timeZone
            formatter.dateStyle = .none
            formatter.timeStyle = .short
            self.init(title: "Your Reel time is up.",
                      message: "Reels are paused until \(formatter.string(from: until)).",
                      detail: "The rest of Instagram still works normally.")
        }
    }
}
