// GENERATED by scripts/build-playgrounds-app.py — edit the original, not this copy.
import Foundation

/// Decides whether the user follows a Reel's creator, using only data that is
/// already on the device: the user's own list of known follows and the hint
/// from the page they are looking at. Nothing is fetched from Instagram.
public struct FollowResolver: Sendable {
    public var knownFollows: Set<String>
    public var usePageHints: Bool
    public var trustMissingFollowButton: Bool

    public init(knownFollows: Set<String>, usePageHints: Bool, trustMissingFollowButton: Bool) {
        self.knownFollows = knownFollows
        self.usePageHints = usePageHints
        self.trustMissingFollowButton = trustMissingFollowButton
    }

    public init(settings: GuardSettings) {
        self.init(
            knownFollows: settings.knownFollows,
            usePageHints: settings.usePageHints,
            trustMissingFollowButton: EffectivePolicy(settings).trustMissingFollowButton
        )
    }

    public func resolve(creator: String?, hint: FollowHint) -> FollowState {
        if let creator, knownFollows.contains(creator.lowercased()) { return .following }
        guard usePageHints else { return .unknown }
        switch hint {
        case .following: return .following
        case .notFollowing: return .notFollowing
        case .noFollowButton: return trustMissingFollowButton && creator != nil ? .following : .unknown
        case .unknown: return .unknown
        }
    }
}
