// GENERATED by scripts/build-playgrounds-app.py — edit the original, not this copy.
import Foundation

/// How the Reel being evaluated relates to what the user was doing.
public enum ReelTransition: Equatable, Sendable {
    /// First Reel after a non-Reel page.
    case entry(EntrySource)
    /// The Reel that is already the current one of the chain (re-render, back swipe).
    case current
    /// A different Reel inside an existing chain — i.e. a swipe.
    case continuation(ReelChain)
}

/// Everything a rule may look at. Rules never see URLs, DM contents or
/// anything beyond these fields.
public struct GuardContext: Sendable {
    public var page: PageKind
    public var sighting: ReelSighting?
    public var transition: ReelTransition?
    public var follow: FollowState
    public var policy: EffectivePolicy
    public var knownFollows: Set<String>
    public var budget: ReelTimeBudget
    public var now: Date
}

public enum RuleVerdict: Equatable, Sendable {
    case allow
    case block(BlockReason)
    /// The rule has no opinion; the next rule decides.
    case abstain
}

/// One filtering mechanism. Rules are evaluated in order and the first
/// non-`abstain` verdict wins; if every rule abstains, Reels are blocked
/// (fail closed) and pages are allowed.
///
/// New mechanisms (for example a per-creator allowlist or a daily Reel count)
/// can be added by writing another `GuardRule` and inserting it into
/// `ReelsGuardEngine.defaultRules`.
public protocol GuardRule: Sendable {
    var name: String { get }
    func verdict(for context: GuardContext) -> RuleVerdict
}

/// Pages that aren't a single Reel: the Reels feed and (in Strict Mode) Explore.
public struct PageRule: GuardRule {
    public let name = "page"
    public init() {}
    public func verdict(for c: GuardContext) -> RuleVerdict {
        guard !c.page.isReel else { return .abstain }
        switch c.page {
        case .reelsFeed: return .block(.reelsFeed)
        case .explore where c.policy.blockExplorePage: return .block(.explore)
        default: return .allow
        }
    }
}

/// The optional Reel time limit.
public struct TimeBudgetRule: GuardRule {
    public let name = "timeBudget"
    public init() {}
    public func verdict(for c: GuardContext) -> RuleVerdict {
        guard c.page.isReel, let until = c.budget.activeCooldown(now: c.now) else { return .abstain }
        return .block(.timeUp(until: until))
    }
}

/// Returning to the Reel that is already allowed is always fine.
public struct CurrentReelRule: GuardRule {
    public let name = "currentReel"
    public init() {}
    public func verdict(for c: GuardContext) -> RuleVerdict {
        c.transition == .current ? .allow : .abstain
    }
}

/// The heart of the app: a swipe to another Reel is only allowed when that
/// Reel is from someone the user follows (or the same creator whose profile
/// the chain started on). Everything else ends the chain.
public struct ContinuationRule: GuardRule {
    public let name = "continuation"
    public init() {}
    public func verdict(for c: GuardContext) -> RuleVerdict {
        guard case let .continuation(chain)? = c.transition else { return .abstain }
        if let anchor = chain.anchorCreator, c.sighting?.creator == anchor, c.policy.allowProfile {
            return .allow
        }
        if c.follow == .following, c.policy.allowFollowed {
            return .allow
        }
        return .block(c.follow == .notFollowing ? .notFollowed : .infiniteScroll)
    }
}

/// The first Reel after a normal page: allowed when the user got there
/// intentionally (DM, shared link, profile, followed account in the feed).
public struct EntryRule: GuardRule {
    public let name = "entry"
    public init() {}
    public func verdict(for c: GuardContext) -> RuleVerdict {
        guard case let .entry(source)? = c.transition else { return .abstain }
        let p = c.policy
        switch source {
        case .directMessage, .sharedLink:
            return p.allowSent ? .allow : .block(.categoryDisabled(.sentToMe))

        case let .profile(username):
            guard p.allowProfile else { return .block(.categoryDisabled(.profiles)) }
            if !p.strict { return .allow }
            let followed = c.follow == .following || c.knownFollows.contains(username)
            return followed ? .allow : .block(.notFollowed)

        case .homeFeed:
            guard p.allowFollowed else { return .block(.categoryDisabled(.following)) }
            switch c.follow {
            case .following: return .allow
            case .notFollowing: return .block(.recommended) // "Suggested for you" in the feed
            case .unknown: return p.strict ? .block(.notFollowed) : .allow
            }

        case .explore, .reelsTab:
            return .block(.recommended)

        case .other:
            return c.follow == .following && p.allowFollowed ? .allow : .block(.recommended)
        }
    }
}
