// GENERATED by scripts/build-playgrounds-app.py — edit the original, not this copy.
import Foundation

/// What a web page *suggests* about whether the user follows a Reel's creator.
///
/// These come from best-effort DOM heuristics in `reels-observer.js` (for
/// example, a visible "Follow" button next to the creator's name). They are
/// signals, not facts: Instagram can change its markup at any time.
public enum FollowHint: String, Codable, Sendable {
    /// The page shows a "Following" label for the creator.
    case following
    /// The page shows a "Follow" button for the creator.
    case notFollowing
    /// The creator was identified but no Follow/Following control was found.
    case noFollowButton
    /// Nothing could be determined.
    case unknown
}

/// The resolved follow status used by the policy.
public enum FollowState: String, Codable, Sendable {
    case following
    case notFollowing
    case unknown
}

/// A Reel that became the active one in the viewer.
public struct ReelSighting: Codable, Equatable, Sendable {
    public var reelID: String
    /// Lower-cased username, if it could be identified.
    public var creator: String?
    public var followHint: FollowHint

    public init(reelID: String, creator: String?, followHint: FollowHint = .unknown) {
        self.reelID = reelID
        self.creator = creator?.lowercased()
        self.followHint = followHint
    }
}

/// How the user arrived at the first Reel of a viewing chain.
public enum EntrySource: Codable, Equatable, Sendable {
    /// Tapped a Reel inside a DM conversation.
    case directMessage
    /// Opened from a link: Reels Guard's "Shared with me" inbox, a pasted link,
    /// or a link opened from another app into a fresh Safari tab.
    case sharedLink
    /// Tapped a Reel on a person's profile.
    case profile(username: String)
    /// Tapped a Reel in the home feed (which mixes followed and suggested posts).
    case homeFeed
    /// Explore grid, search grid, audio page.
    case explore
    /// The Reels tab.
    case reelsTab
    /// Posts, stories, anything else.
    case other

    init(previousPage: PageKind?) {
        switch previousPage {
        case nil: self = .sharedLink
        case .directThread?, .directInbox?: self = .directMessage
        case let .profile(username)?: self = .profile(username: username)
        case .home?: self = .homeFeed
        case .explore?: self = .explore
        case .reelsFeed?: self = .reelsTab
        case .reel?, .post?, .stories?, .other?: self = .other
        }
    }
}

/// One Reel-viewing session that started from an intentional entry.
public struct ReelChain: Codable, Equatable, Sendable {
    public var entry: EntrySource
    public var currentReelID: String
    public var length: Int
    /// When the chain started on a profile, swiping through that same
    /// creator's Reels counts as intentional.
    public var anchorCreator: String?
}

/// Per-tab / per-web-view navigation state. Owned by the caller and passed
/// back in on every event, which keeps the engine a pure function.
public struct GuardState: Codable, Equatable, Sendable {
    /// The most recent non-Reel page. Used to work out how a Reel was entered.
    public var lastPage: PageKind?
    public var chain: ReelChain?
    public var activeReelID: String?
    /// Whether watch time for the active Reel should count against the limit.
    public var activeReelAllowed: Bool

    public init(lastPage: PageKind? = nil, chain: ReelChain? = nil, activeReelID: String? = nil, activeReelAllowed: Bool = false) {
        self.lastPage = lastPage
        self.chain = chain
        self.activeReelID = activeReelID
        self.activeReelAllowed = activeReelAllowed
    }
}

/// Something the observer reported.
public enum GuardEvent: Equatable, Sendable {
    /// The user navigated to a page.
    case page(PageKind)
    /// A Reel became the active one (URL change or a different video started playing).
    case reel(ReelSighting)
    /// An allowed Reel has been playing for this many seconds.
    case watchTick(seconds: Double)
}

public enum ReelCategory: String, Codable, Sendable {
    case following
    case sentToMe
    case profiles
}

public enum BlockReason: Codable, Equatable, Sendable {
    /// The `/reels/` feed itself.
    case reelsFeed
    /// The Explore page while Strict Mode is on.
    case explore
    /// A Reel entered from an algorithmic surface (Reels tab, Explore, suggestions).
    case recommended
    /// The next Reel is known not to be from an account the user follows.
    case notFollowed
    /// The next Reel couldn't be confirmed as coming from a followed account.
    case infiniteScroll
    /// Swiped past a Reel that was sent to the user. Sent Reels play on their own.
    case endOfSentReel
    /// The user switched this category off.
    case categoryDisabled(ReelCategory)
    /// The Reel time limit is used up.
    case timeUp(until: Date)
}

public enum GuardDecision: Codable, Equatable, Sendable {
    case allow
    case block(BlockReason)

    public var isAllowed: Bool { self == .allow }
}
