// GENERATED by scripts/build-playgrounds-app.py — edit the original, not this copy.
import Foundation

/// The kind of instagram.com page a URL points at.
///
/// This is the only "inspection" Reels Guard performs that is fully reliable:
/// it is derived from the public URL structure of instagram.com. It works
/// inside the app's own web view and inside Safari (via the web extension).
/// It can NOT be applied to the native Instagram app, which exposes no URLs or
/// UI to other apps.
public enum PageKind: Codable, Equatable, Hashable, Sendable {
    /// `/` — the home feed.
    case home
    /// `/reels/` with no reel id — the endless recommendation feed.
    case reelsFeed
    /// `/reel/<id>/`, `/reels/<id>/`, `/tv/<id>/` or `/<user>/reel/<id>/`.
    case reel(id: String, author: String?)
    /// `/p/<id>/` or `/<user>/p/<id>/`.
    case post
    /// `/explore/…`, including search grids, tags, locations and audio pages.
    case explore
    /// `/direct/inbox/` and other DM list pages.
    case directInbox
    /// `/direct/t/<thread>/` — a DM conversation. The thread id is never stored.
    case directThread
    /// `/<username>/`, `/<username>/reels/`, `/<username>/tagged/`.
    case profile(username: String)
    /// `/stories/…`.
    case stories
    /// Anything else (settings, login, non-Instagram hosts…).
    case other

    public var isReel: Bool {
        if case .reel = self { return true }
        return false
    }

    public var reelID: String? {
        if case let .reel(id, _) = self { return id }
        return nil
    }
}

public enum InstagramURLClassifier {
    public static let hosts: Set<String> = ["instagram.com", "www.instagram.com", "m.instagram.com"]

    /// First path segments that are Instagram routes rather than usernames.
    /// Keep in sync with `RESERVED` in `Shared/WebGuard/reels-observer.js`.
    public static let reservedSegments: Set<String> = [
        "accounts", "about", "api", "ajax", "archive", "challenge", "data", "developer",
        "direct", "directory", "emails", "explore", "graphql", "legal", "locations",
        "notifications", "oauth", "p", "privacy", "reel", "reels", "session", "settings",
        "static", "stories", "topics", "tv", "web", "your_activity",
    ]

    public static func isInstagram(_ url: URL) -> Bool {
        guard let host = url.host?.lowercased() else { return false }
        return hosts.contains(host)
    }

    public static func isUsername(_ segment: String) -> Bool {
        guard (1...30).contains(segment.count) else { return false }
        guard !reservedSegments.contains(segment.lowercased()) else { return false }
        return segment.allSatisfy { $0.isASCII && ($0.isLetter || $0.isNumber || $0 == "." || $0 == "_") }
    }

    public static func classify(_ string: String) -> PageKind {
        guard let url = URL(string: string) else { return .other }
        return classify(url)
    }

    public static func classify(_ url: URL) -> PageKind {
        guard isInstagram(url) else { return .other }
        let segments = url.path.split(separator: "/").map(String.init)
        guard let first = segments.first else { return .home }
        let second = segments.count > 1 ? segments[1] : nil
        let third = segments.count > 2 ? segments[2] : nil

        switch first.lowercased() {
        case "reels":
            if second?.lowercased() == "audio" { return .explore }
            if let id = second { return .reel(id: id, author: nil) }
            return .reelsFeed
        case "reel", "tv":
            if let id = second { return .reel(id: id, author: nil) }
            return .reelsFeed
        case "p":
            return .post
        case "explore":
            return .explore
        case "direct":
            return second?.lowercased() == "t" ? .directThread : .directInbox
        case "stories":
            return .stories
        default:
            guard isUsername(first) else { return .other }
            let username = first.lowercased()
            switch second?.lowercased() {
            case "reel", "reels", "tv":
                if let id = third { return .reel(id: id, author: username) }
                return .profile(username: username)
            case "p":
                return .post
            case nil, "tagged", "saved", "followers", "following":
                return .profile(username: username)
            default:
                return .other
            }
        }
    }
}
