// GENERATED by scripts/build-playgrounds-app.py — edit the original, not this copy.
import Foundation

/// Message sent by `reels-observer.js`. Same format for the in-app web view
/// and the Safari extension.
public struct WireRequest: Codable, Equatable, Sendable {
    public enum Kind: String, Codable, Sendable {
        case page, reel, tick, profile
    }

    public var type: Kind
    public var url: String?
    public var reelID: String?
    public var creator: String?
    public var followHint: FollowHint?
    public var seconds: Double?
    /// For `profile`: the username of the profile being viewed and whether the
    /// page shows "Following".
    public var username: String?
    public var following: Bool?
    /// Opaque `GuardState` round-tripped by stateless hosts (Safari extension).
    public var stateJSON: String?

    public init(type: Kind, url: String? = nil, reelID: String? = nil, creator: String? = nil,
                followHint: FollowHint? = nil, seconds: Double? = nil, username: String? = nil,
                following: Bool? = nil, stateJSON: String? = nil) {
        self.type = type
        self.url = url
        self.reelID = reelID
        self.creator = creator
        self.followHint = followHint
        self.seconds = seconds
        self.username = username
        self.following = following
        self.stateJSON = stateJSON
    }
}

public struct WireResponse: Codable, Equatable, Sendable {
    public var decision: String // "allow" | "block"
    public var block: BlockScreenCopy?
    public var stateJSON: String?

    public static let allow = WireResponse(decision: "allow", block: nil, stateJSON: nil)
}

/// Glue between the wire format, persistence and the pure engine. Each
/// enforcement surface owns one of these.
public final class ReelsGuardService: @unchecked Sendable {
    public let store: SharedStore
    public let engine: ReelsGuardEngine
    private let clock: () -> Date

    public init(store: SharedStore = SharedStore(), engine: ReelsGuardEngine = ReelsGuardEngine(), clock: @escaping () -> Date = Date.init) {
        self.store = store
        self.engine = engine
        self.clock = clock
    }

    /// Handles one observer message for a host that keeps `GuardState` itself.
    public func handle(_ request: WireRequest, state: GuardState) -> (decision: GuardDecision, state: GuardState) {
        let settings = store.loadSettings()

        let event: GuardEvent
        switch request.type {
        case .profile:
            if let username = request.username?.lowercased(), let following = request.following,
               settings.learnFollowsFromProfiles, InstagramURLClassifier.isUsername(username) {
                learnFollow(username, following: following)
            }
            return (.allow, state)
        case .tick:
            event = .watchTick(seconds: request.seconds ?? 0)
        case .page:
            event = .page(InstagramURLClassifier.classify(request.url ?? ""))
        case .reel:
            let urlKind = InstagramURLClassifier.classify(request.url ?? "")
            guard let reelID = request.reelID ?? urlKind.reelID else { return (.allow, state) }
            var urlAuthor: String?
            if case let .reel(_, author) = urlKind { urlAuthor = author }
            event = .reel(ReelSighting(reelID: reelID, creator: request.creator ?? urlAuthor,
                                       followHint: request.followHint ?? .unknown))
        }

        let budget = store.loadBudget()
        let outcome = engine.process(event, state: state, settings: settings, budget: budget, now: clock())
        if outcome.budget != budget { store.saveBudget(outcome.budget) }
        return (outcome.decision, outcome.state)
    }

    /// Handles a message for a stateless host: state travels in `stateJSON`.
    public func handleStateless(_ request: WireRequest) -> WireResponse {
        let decoder = JSONDecoder()
        let state = request.stateJSON.flatMap { try? decoder.decode(GuardState.self, from: Data($0.utf8)) } ?? GuardState()
        let result = handle(request, state: state)
        var response = Self.response(for: result.decision)
        if let data = try? JSONEncoder().encode(result.state) {
            response.stateJSON = String(decoding: data, as: UTF8.self)
        }
        return response
    }

    /// Dictionary-in / dictionary-out convenience for `WKScriptMessage.body`
    /// and Safari's `SFExtensionMessageKey` payloads.
    public func handleStateless(message: Any?) -> [String: Any] {
        guard let request = Self.decodeRequest(message) else { return Self.dictionary(.allow) }
        return Self.dictionary(handleStateless(request))
    }

    public static func response(for decision: GuardDecision) -> WireResponse {
        switch decision {
        case .allow: return .allow
        case let .block(reason): return WireResponse(decision: "block", block: BlockScreenCopy(reason: reason), stateJSON: nil)
        }
    }

    public static func decodeRequest(_ message: Any?) -> WireRequest? {
        guard let message, JSONSerialization.isValidJSONObject(message),
              let data = try? JSONSerialization.data(withJSONObject: message) else { return nil }
        return try? JSONDecoder().decode(WireRequest.self, from: data)
    }

    public static func dictionary(_ response: WireResponse) -> [String: Any] {
        guard let data = try? JSONEncoder().encode(response),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return ["decision": "allow"]
        }
        return object
    }

    private func learnFollow(_ username: String, following: Bool) {
        store.updateSettings { settings in
            var learned = Set(settings.learnedFollows)
            if following { learned.insert(username) } else { learned.remove(username) }
            let sorted = learned.sorted()
            if sorted != settings.learnedFollows { settings.learnedFollows = sorted }
        }
    }
}
