// GENERATED by scripts/build-playgrounds-app.py — edit the original, not this copy.
import SwiftUI

/// The interruption. Plain on purpose: no illustration, no animation, no
/// counters, and no button that leads to another Reel.
struct BlockScreenView: View {
    let copy: BlockScreenCopy
    let onBack: () -> Void

    var body: some View {
        ZStack {
            Color(uiColor: .systemGroupedBackground)
                .ignoresSafeArea()
            VStack(spacing: 12) {
                Text(copy.title)
                    .font(.title2.weight(.semibold))
                Text(copy.message)
                Text(copy.detail)
                    .font(.subheadline)
                    .foregroundStyle(.secondary)
                    .padding(.bottom, 20)
                Button(copy.buttonTitle, action: onBack)
                    .buttonStyle(.borderedProminent)
                    .controlSize(.large)
            }
            .multilineTextAlignment(.center)
            .padding(32)
            .frame(maxWidth: 380)
        }
        .accessibilityElement(children: .contain)
        .accessibilityAddTraits(.isModal)
    }
}
