// GENERATED by scripts/build-playgrounds-app.py — edit the original, not this copy.
import SwiftUI

/// Opens straight into Instagram. Settings live in their own tab.
struct RootView: View {
    enum Tab: Hashable {
        case instagram
        case settings
    }

    @EnvironmentObject private var model: SettingsModel
    @StateObject private var browser: GuardedBrowserModel
    @State private var tab: Tab = .instagram

    init(service: ReelsGuardService) {
        _browser = StateObject(wrappedValue: GuardedBrowserModel(service: service, startURL: nil))
    }

    var body: some View {
        TabView(selection: $tab) {
            GuardedBrowserView(model: browser)
                .tabItem { Label("Instagram", systemImage: "play.rectangle") }
                .tag(Tab.instagram)
            ControlView()
                .tabItem { Label("Settings", systemImage: "gearshape") }
                .tag(Tab.settings)
        }
        .onChange(of: model.pendingOpen) { _, url in
            guard let url else { return }
            model.pendingOpen = nil
            tab = .instagram
            browser.openShared(url)
        }
        .onChange(of: tab) { _, newTab in
            // Pick up the Reel timer and anything learned while browsing.
            if newTab == .settings { model.reload() }
        }
    }
}
