#!/usr/bin/env python3
"""Assembles Userscript/reels-guard.user.js from the shared web sources.

The userscript runs Reels Guard on instagram.com in Safari through the free
"Userscripts" App Store app: no sideloading, nothing expires.

Usage: scripts/build-userscript.py [--check]
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
WEB = ROOT / "Shared/WebGuard"
OUTPUT = ROOT / "Userscript/reels-guard.user.js"
VERSION = "1.0.0"  # bump when the script changes, so Userscripts offers the update
RAW = "https://raw.githubusercontent.com/kingmcclavin/codes/claude/reels-guard-ios/ReelsGuard/Userscript/reels-guard.user.js"
PARTS = ["reels-observer.js", "reels-policy.js", "block-overlay.js", "userscript-host.js"]

HEADER = f"""// ==UserScript==
// @name         Reels Guard
// @namespace    https://github.com/kingmcclavin/codes
// @version      {VERSION}
// @description  Instagram without the Reels feed. Reels you open from messages, profiles and people you follow still play; scrolling into recommendations is blocked.
// @match        https://www.instagram.com/*
// @match        https://instagram.com/*
// @run-at       document-start
// @inject-into  content
// @grant        none
// @noframes
// @updateURL    {RAW}
// @downloadURL  {RAW}
// ==/UserScript==

// GENERATED by scripts/build-userscript.py from Shared/WebGuard/. Edit those files, not this one.
"""


def build() -> str:
    body = "\n".join(f"// ---- {name} ----\n{(WEB / name).read_text().rstrip()}\n" for name in PARTS)
    return HEADER + "\n" + body


def main() -> None:
    text = build()
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != text:
            print(f"Out of date: {OUTPUT.relative_to(ROOT)}\nRun scripts/build-userscript.py")
            sys.exit(1)
        print("Up to date.")
        return
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text)
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(text)} bytes)")


if __name__ == "__main__":
    main()
