#!/usr/bin/env python3
"""Regenerates derived sources. Run after changing app or core code.

1. App/Sources/Browser/ObserverScript.swift
   Shared/WebGuard/reels-observer.js embedded as a Swift string, so the app
   doesn't depend on bundle resources.
2. ReelsGuard.swiftpm/
   A single-module Swift Playgrounds app (iPad / Mac) built from:
     Packages/ReelsGuardCore/Sources/ReelsGuardCore  -> Core/
     App/Sources (except Platform/)                  -> App/
     PlaygroundsSupport/                             -> Package.swift, Platform/
   Swift Playgrounds can't build app extensions or use the Family Controls
   entitlement, so that build contains the in-app browser only.

Usage: scripts/build-playgrounds-app.py [--check]
  --check  exit 1 if anything is out of date, without writing.
"""
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OBSERVER_JS = ROOT / "Shared/WebGuard/reels-observer.js"
OBSERVER_SWIFT = ROOT / "App/Sources/Browser/ObserverScript.swift"
CORE = ROOT / "Packages/ReelsGuardCore/Sources/ReelsGuardCore"
APP = ROOT / "App/Sources"
SUPPORT = ROOT / "PlaygroundsSupport"
OUTPUT = ROOT / "ReelsGuard.swiftpm"

HEADER = "// GENERATED by scripts/build-playgrounds-app.py — edit the original, not this copy.\n"


def observer_swift() -> str:
    js = OBSERVER_JS.read_text()
    if '"##' in js:
        sys.exit("reels-observer.js contains '\"##', which would end the Swift raw string")
    return (
        "// GENERATED from Shared/WebGuard/reels-observer.js by scripts/build-playgrounds-app.py.\n"
        "// Do not edit; edit the .js file and rerun the script.\n\n"
        "enum ObserverScript {\n"
        '    static let source = ##"""\n'
        f"{js.rstrip()}\n"
        '"""##\n'
        "}\n"
    )


def playgrounds_files() -> dict:
    files = {}
    for path in sorted(CORE.glob("*.swift")):
        files[f"Core/{path.name}"] = path.read_text()
    for path in sorted(APP.rglob("*.swift")):
        rel = path.relative_to(APP)
        if rel.parts[0] == "Platform":
            continue
        files[f"App/{rel.as_posix()}"] = path.read_text()
    # Always the freshly generated text, even before ObserverScript.swift exists.
    files[f"App/{OBSERVER_SWIFT.relative_to(APP).as_posix()}"] = OBSERVER_SWIFT_TEXT
    for path in sorted(SUPPORT.rglob("*.swift")):
        rel = path.relative_to(SUPPORT).as_posix()
        files[rel] = path.read_text()

    result = {}
    for rel, text in files.items():
        # One module: drop imports of the core package.
        lines = [l for l in text.splitlines(keepends=True) if l.strip() != "import ReelsGuardCore"]
        body = "".join(lines)
        result[rel] = body if rel == "Package.swift" else HEADER + body
    return result


def tree(path: Path) -> dict:
    if not path.exists():
        return {}
    return {p.relative_to(path).as_posix(): p.read_text() for p in path.rglob("*") if p.is_file()}


OBSERVER_SWIFT_TEXT = observer_swift()


def main() -> None:
    check = "--check" in sys.argv
    wanted = playgrounds_files()
    stale = []
    if not OBSERVER_SWIFT.exists() or OBSERVER_SWIFT.read_text() != OBSERVER_SWIFT_TEXT:
        stale.append(str(OBSERVER_SWIFT.relative_to(ROOT)))
    if tree(OUTPUT) != wanted:
        stale.append(str(OUTPUT.relative_to(ROOT)))

    if check:
        if stale:
            print("Out of date: " + ", ".join(stale) + "\nRun scripts/build-playgrounds-app.py")
            sys.exit(1)
        print("Up to date.")
        return

    OBSERVER_SWIFT.write_text(OBSERVER_SWIFT_TEXT)
    with tempfile.TemporaryDirectory() as tmp:
        staging = Path(tmp) / "out"
        for rel, text in wanted.items():
            target = staging / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text)
        if OUTPUT.exists():
            shutil.rmtree(OUTPUT)
        shutil.copytree(staging, OUTPUT)
    print(f"Wrote {OBSERVER_SWIFT.relative_to(ROOT)} and {OUTPUT.relative_to(ROOT)}/ ({len(wanted)} files)")


if __name__ == "__main__":
    main()
