// GENERATED by scripts/build-playgrounds-app.py — edit the original, not this copy.
import SwiftUI
import WebKit

struct GuardedBrowserView: View {
    @StateObject private var model: GuardedBrowserModel
    @Environment(\.dismiss) private var dismiss

    init(service: ReelsGuardService, startURL: URL?) {
        _model = StateObject(wrappedValue: GuardedBrowserModel(service: service, startURL: startURL))
    }

    var body: some View {
        NavigationStack {
            WebViewContainer(webView: model.webView)
                .ignoresSafeArea(edges: .bottom)
                .overlay {
                    if let copy = model.blockCopy {
                        BlockScreenView(copy: copy) { model.backToInstagram() }
                    }
                }
                .navigationTitle("Instagram")
                .navigationBarTitleDisplayMode(.inline)
                .toolbar {
                    ToolbarItem(placement: .confirmationAction) {
                        Button("Done") { dismiss() }
                    }
                    ToolbarItem(placement: .topBarLeading) {
                        Button {
                            model.goBack()
                        } label: {
                            Image(systemName: "chevron.backward")
                        }
                        .disabled(!model.canGoBack || model.blockCopy != nil)
                        .accessibilityLabel("Back")
                    }
                }
        }
    }
}

private struct WebViewContainer: UIViewRepresentable {
    let webView: WKWebView

    func makeUIView(context: Context) -> WKWebView { webView }
    func updateUIView(_ uiView: WKWebView, context: Context) {}
}
