// GENERATED by scripts/build-playgrounds-app.py — edit the original, not this copy.
import SwiftUI
import WebKit

/// The Instagram tab: instagram.com, edge to edge, with the blocking screen on
/// top when needed. Swipe from the left edge to go back.
struct GuardedBrowserView: View {
    @ObservedObject var model: GuardedBrowserModel

    var body: some View {
        WebViewContainer(webView: model.webView)
            .overlay {
                if let copy = model.blockCopy {
                    BlockScreenView(copy: copy) { model.backToInstagram() }
                }
            }
    }
}

private struct WebViewContainer: UIViewRepresentable {
    let webView: WKWebView

    func makeUIView(context: Context) -> WKWebView { webView }
    func updateUIView(_ uiView: WKWebView, context: Context) {}
}
