#!/bin/sh
# Generates Playground/TI84Emulator.swiftpm, a Swift Playgrounds app project
# (for building and running on an iPad without a Mac), from the package
# sources. Re-run after changing anything in Sources/.
#
# Swift Playgrounds app projects are a single module, so the core and UI
# sources are copied into one target: cross-module imports are removed, and
# the ROM is supplied through the app's "Import ROM…" button (Bundle.main
# lookup) instead of a package resource.
set -eu
cd "$(dirname "$0")/.."

OUT=Playground/TI84Emulator.swiftpm
rm -rf "$OUT"
mkdir -p "$OUT/Core" "$OUT/UI"

copy() {
    # $1 = source dir, $2 = destination dir
    find "$1" -name '*.swift' | while read -r file; do
        name=$(echo "${file#$1/}" | tr '/' '_')
        sed -e '/^import TI84EmulatorCore$/d' \
            -e '/^@testable import TI84EmulatorCore$/d' \
            -e 's/Bundle\.module/Bundle.main/g' \
            "$file" > "$2/$name"
    done
}

copy Sources/TI84EmulatorCore "$OUT/Core"
copy Sources/TI84EmulatorUI "$OUT/UI"
rm -f "$OUT/UI/Module.swift" "$OUT/Core/CPU_CPMHarness.swift"

cat > "$OUT/App.swift" <<'SWIFT'
import SwiftUI

@main
struct TI84EmulatorApp: App {
    var body: some Scene {
        WindowGroup {
            CalculatorRootView()
        }
    }
}
SWIFT

cat > "$OUT/Package.swift" <<'SWIFT'
// swift-tools-version: 5.8

// Swift Playgrounds app project. Generated by Scripts/make-playground.sh.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TI-84 Emulator",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "TI-84 Emulator",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.ti84emulator",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .calculator),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
SWIFT

echo "Generated $OUT"
