// swift-tools-version: 5.8

// Swift Playgrounds app project. Generated by Scripts/make-playground.sh.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "TI-84 Emulator",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "TI-84 Emulator",
            targets: ["AppModule"],
            bundleIdentifier: "com.example.ti84emulator",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .calculator),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
